---

##################################################
# Timezone #######################################
##################################################

# Check http://manpages.ubuntu.com/manpages/bionic/man3/DateTime::TimeZone::Catalog.3pm.html
TIMEZONE: Europe/Bratislava

##################################################
# PHP ############################################
##################################################

PHP_DISPLAY_ERRORS: On
PHP_MEMORY_LIMIT: 256M
